### ISSUE TITLE
[Suggestion] New mode: Function Only

### ISSUE THREAD

**Issue by LeeroyGarfield** [RubixDev/Inventorio#105]
Hello, amazing and useful mod! I have a suggestion:

There are three modes in Segmented Hotbar Mode: "No," "Visual Only," and "Yes." So, I'm wondering if it's possible to add a new mode called "Function Only"? It keeps the hotbar's original layout, but it functions like "Yes" segmented hotbar mode.

**Comment by RubixDev** [comment]
Support for this was added in 7c53a5f74605df56bfe72bbd44fcce4cff701fef over a year ago
