### ISSUE TITLE
Incompatibility with Backpacked

### ISSUE THREAD

**Issue by ArrowGamez** [RubixDev/Inventorio#111]
When having Backpacked and Inventorio installed together upon death it deletes everything from Inventorios pockets, toolbelt, and utility belt. Im not really sure as to why unless its due to the fact that Backpacked adds in a slot in the inventory for you to put the Backpack. But I would really love to play with both mods as I love your inventory system, but I also love the customization and functionality that Backpacked brings, please let me know if you can either patch this or if you know of a solution or way around it, or if its something I would need to talk to the creator of Backpacked about. Thank you for your time.

**Comment by Lizard-Of-Oz** [comment]
I think it would take some work on the Backpacked's end. Inventorio provides an API which should be sufficient enough to allow such changes.

**Comment by ArrowGamez** [comment]
Ok, ill message them then and see if I can get the issue resolved, thanks for the help!

**Comment by ArrowGamez** [comment]
Talked to the creator of Backpacked and for anyone who has this issue installing curios api fixes the problem!

**Comment by RubixDev** [comment]
well this seems to be resolved
