### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by maxface14** [RubixDev/Inventorio#118]
Hi! I've created a dark theme for Inventorio. It's based on nachoholtz's [DarkUI Extended](https://www.curseforge.com/minecraft/texture-packs/dark-mode-gui). I've also reached out to nachoholtz to add Inventorio support to the resource pack.

I only modified player_inventory.png because widgets.png was already dark enough. Here's the modified texture.
![player_inventory_DarkUI](https://user-images.githubusercontent.com/101950728/169159421-89c5f3af-8051-4824-9419-3784b6f01ca9.png)

**Comment by maxface14** [comment]
Thanks for incorporating this! I'm a big fan of the mod (it's the only reason I'm running 1.18.2 instead of 1.18.1 haha) so if you ever need any pro bono graphic design help, I'm happy to provide! Discord is maxface#8144

**Comment by RubixDev** [comment]
This was added in 7c53a5f74605df56bfe72bbd44fcce4cff701fef over a year ago
