### ISSUE TITLE
add support for Curios API/ Extreme sound muffler/ Cosmetic Armor Reworked/ TrashSlot [FORGE]

### ISSUE THREAD

**Issue by vindocel** [RubixDev/Inventorio#201]
![amostra](https://user-images.githubusercontent.com/18473368/207074202-37594275-b03b-41fe-a352-29621ac42432.png)
===
screenshots taken from version 1.19.2 Forge
[Curios API](https://www.curseforge.com/minecraft/mc-mods/curios) ----------------------/ [github](https://github.com/TheIllusiveC4/Curios)
[Extreme sound muffler](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler) --------/ [github](https://github.com/LeoBeliik/ExtremeSoundMuffler)
[Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked) ----/ [github](https://github.com/zlainsama/CosmeticArmorReworked)
[TrashSlot](https://www.curseforge.com/minecraft/mc-mods/trashslot) -----------------------/ [github](https://github.com/TwelveIterationMods/TrashSlot)

**Comment by Wubzzz1337** [comment]
Hope this gets added soonish :o

**Comment by RubixDev** [comment]
Closing in favor of #318
