### ISSUE TITLE
[Suggestion] Armor slots in every container for easy access.

### ISSUE THREAD

**Issue by K0-RR** [RubixDev/Inventorio#21]
This way you can change your armor without opening different GUIs a few times.
Like this https://www.curseforge.com/minecraft/mc-mods/cpas/screenshots

**Comment by Lizard-Of-Oz** [comment]
Adding something to every GUI would be a compatibility nightmare. I had to cut out some originally planned features (discussed here: https://youtu.be/XJmlAsdC5Sc) due to the compatibility issues.
This is why Deep Pockets slots are also inaccessible in any other UI than Player's Inventory.

**Comment by Lizard-Of-Oz** [comment]
Is it compatible with my mod btw? If so, then "use both mods" is a solution.
