### ISSUE TITLE
Publish on modrinth

### ISSUE THREAD

**Issue by ascpial** [RubixDev/Inventorio#245]
I want to publish a modpack on modrinth with your mod included, however Curseforge disallowed Modrinth from referencing Curseforge mods and projects, so I will reference a Github build instead.

It would even be better if you publish your mod on modrinth, which will slightly increase the reach of the project.

If you want, I can provide github actions to automatically upload the updates to both Curseforge and Modrinth, as well as Github releases.

**Comment by Lizard-Of-Oz** [comment]
Will do later this summer. Also, be advised: unless you somehow compile from github sources directly, the old (and now deleted) builds are severely outdated.

**Comment by ascpial** [comment]
Thanks for the advice.

If github does not have up-to-date builds, do you allow me to put the jar directly in the mdopack until you publish the project on modrinth?

**Comment by Lizard-Of-Oz** [comment]
Go ahead.

**Comment by Enderteck** [comment]
Any updates ?

I don't find the mod in the modrinth app.

Love ya

**Comment by Lizard-Of-Oz** [comment]
Not yet - busy with other stuff

**Comment by RubixDev** [comment]
[Inventorio is available on Modrinth now!](https://modrinth.com/mod/inventorio)

**Comment by Enderteck** [comment]
Nice !
