### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [RubixDev/Inventorio#246]
Apply selected profile is not available. I click the button but nothing changes.
![sss1](https://github.com/Lizard-Of-Oz/Inventorio/assets/122460325/02116c31-1ce3-4f31-8996-1c253f7b2f9d)
versiyon; [1.20+] Inventorio 1.9.2 fabric
[Uploading 2023-07-20-1.log…]()

**Comment by Lizard-Of-Oz** [comment]
Please report it to the author of the mod that introduced this feature.
Also, the recipe book is apparently on top of the button that should enable vanilla inventory for compatibility cases like these. I guess that's yet another mod doing it.

**Comment by Rogenar** [comment]
This bug is causing a conflict with trinkets mod I guess. I removed the inventorio mod and tried it like that, the trinkets slots are open again

**Comment by Rogenar** [comment]
So how to fix this situation now?

**Comment by Lizard-Of-Oz** [comment]
Locate whatever mod is moving the crafting book button, or use a mod that deletes it outright, and press the toggle button when you want to swap the Trinkets. https://www.curseforge.com/minecraft/mc-mods/no-recipe-book

**Comment by Rogenar** [comment]
Only this mod remained in version 1.15.2.

**Comment by Lizard-Of-Oz** [comment]
Oh, sorry. Well, sadly I can't fix the issue on Inventorio's end. I tried.

**Comment by Rogenar** [comment]
Let's report this issue to the trinkets mod maker.

**Comment by Rogenar** [comment]
I reported the same issue to the Trinkets mod maker, but I did not get any response.

**Comment by Rogenar** [comment]
emilyploszaj; This is not something trinkets can reasonably fix, it's the responsibility of inventorio.
This gave the answer.

**Comment by Lizard-Of-Oz** [comment]
Well, yeah. It would require too much work on either end, and neither can justify it. Trinkets and Inventorio will remain "semi-compatible", in a sense that you can access Trinkets via that button, but without nice integration.
Unfortunately, I don't have the time to commit to the mod. Maybe eventually I'll add the option to move the toggle button - probably with MC 1.21.

**Comment by Rogenar** [comment]
There is still time for version 1.21 to arrive. Also the mod pack I created is 1.20.1. If this isn't going to stop and fix it, I'll have to unpack your mod. Because Trinket provides many mods to run.

**Comment by RubixDev** [comment]
Closing in favor of #318
