### ISSUE TITLE
Offhand items persist after death, except for the one held which gets deleted.

### ISSUE THREAD

**Issue by mutantfrogs** [RubixDev/Inventorio#263]

**Comment by Lizard-Of-Oz** [comment]
Likely a compatibility issue with other mods. If you suspect any such mod in particular, let me know.

**Comment by mutantfrogs** [comment]
I think it might be a compatibility issue with vanilla tweaks graves then. Thanks for pointing that out!

**Comment by RubixDev** [comment]
There's nothing Inventorio can do about that, and I don't think VanillaTweaks can do much about that either. I suggest using a compatible grave mod instead, such as Universal Graves or Forgotten Graves
