### ISSUE TITLE
Items picked up will create new stack in inventory when utility slot already has a non-full stack made.

### ISSUE THREAD

**Issue by Sugar-Pink** [RubixDev/Inventorio#265]
Basically if I have torches x32 in my utility hand and I place one, then break it, it will not return to my utility hand and instead create a new stack in my inventory and I have to manually place it back in my utility stack.

**Comment by lucascoelho07** [comment]
Duplicate of #305 ?

**Comment by RubixDev** [comment]
> Duplicate of https://github.com/RubixDev/Inventorio/issues/305 (already fixed)?

indeed.

This bug was introduced in the 1.20 port and was fixed again in v1.10.0
