### ISSUE TITLE
Losing Tools on Death

### ISSUE THREAD

**Issue by s0ggx** [RubixDev/Inventorio#280]
hi ive been losing all the tools within the tool slots whenever i die...i love this mod so much but this is a big issue, not sure if its a mod compatibility issue or something, didnt work with graves mod so i removed it, now i died with a mod to drop items in one spot and it didnt work again, ill take it out and see if its those mods

**Comment by s0ggx** [comment]
UPDATE: yes it was the Easy Death mod, seems like any mods that changes how items drop severely effects the tool/offhand slots

**Comment by RubixDev** [comment]
This will have to be reported to the Easy Death / Grave mods. Inventorio provides an API they can use, and for Fabric there are already some grave mods supporting Inventorio (I know about Forgotten Graves, "You're in Grave Danger", and Universal Graves).
