### ISSUE TITLE
[Request] Inventorio Client Only

### ISSUE THREAD

**Issue by AleksKhaos** [RubixDev/Inventorio#285]
i dont know if its too much to ask but wouldn't be great if this mod could be a client only mod? like, only using the utility bar, tool belt and the extra space, without the enchantment & i think the extended ender chest as well.

i love this mod and i would love to use it on servers but most of the server i play [hosted by me or my friends] wont allow it because of cross-platform and/or people just dont wanting to download the mod.

it would be great if there was a Client Only Mode like this i already talked about, and the normal one, Client & Server side mode.

i didn't do much of a research so i dont know if it was asked before or if there is an unknown client only mod like this [if its there please tell me what it is]

i hope this request can be found by the developer and i hope its not that much to ask.

**Comment by Enderteck** [comment]
Probably impossible as the server you would be playing on would not understand what the mod is asking it to do, as it is not installed there. You need the mod on the server side too. Would also be considered a cheat if only required client-side

**Comment by RubixDev** [comment]
As @Enderteck said, this is impossible to have as a client-side only mod, except for maybe a handful features like the split hotbar.
