### ISSUE TITLE
Incompatibility with Alex's Cave's Galena Gauntlet

### ISSUE THREAD

**Issue by BoardAnims** [RubixDev/Inventorio#294]
Apart from the shovel and sword which seem to work fine, the pickaxe and axe will not mine when the gauntlet is activated alongside them.

The tool magnetizes forward as normal but as soon as it hits a surface (like stone or wood) the tool mines for half a second before being retreated back to the user. Normally its supposed to stay there, mining at the blocks it is being pointed at until canceled.
Not sure why this only happens with those two specific tools...

Also, whenever a tool is recalled back to the user, it doesn't go back to the utility belt, rather the hotbar as if it was being picked up from the ground. I'm not sure if this is intentional from the original mod but it's gonna be annoying constantly having to put the tool back in the offhand.

**Comment by SireAwfulThe1st** [comment]
I don't have the same issue, but I just wanna point out that adding tae this incompability, the animation is also bugged out with inventorio's toolbar/offhand.

**Comment by BoardAnims** [comment]
An Inventorio or Alex's Caves update seems to have fixed this issue. I can now use magnetized tools seemingly as normal. 

The only thing that's annoying is that after you recall a tool from your utlity belt, the tool will go to your inventory instead of the utility belt. This however, seems to be an Alex's Caves thing, since without Inventorio, the tool will also not go back to your offhand.
