### ISSUE TITLE
Jade causes tools to be selected from just looking at blocks

### ISSUE THREAD

**Issue by SireAwfulThe1st** [RubixDev/Inventorio#296]
![Screenshot (354)](https://github.com/Lizard-Of-Oz/Inventorio/assets/106896635/f6e2dd69-ec1e-4c42-a529-9edd1e094ea7)
It looks like after an update or so, suddenly the tools that are automatically switched onto the correct blocks will now permanently stay on your hand instantly of only being triggered when trying to mine with said blocks, is there a way to turn off this glitch/bug/new feature? its kinda annoying that the tools are now always triggered instead of only being triggered when you specifically mine like before. Hopefully this is a bug since I didn't remember it works out like this.

**Comment by Poundcaked** [comment]
I'm pretty sure you have the mod "Jade", which I found out causes this.

**Comment by SireAwfulThe1st** [comment]
> I'm pretty sure you have the mod "Jade", which I found out causes this.

Thanks alot for identifying it? which config that caused this so I may turn whatever causing this off?

**Comment by SireAwfulThe1st** [comment]
> I'm pretty sure you have the mod "Jade", which I found out causes this.

Thanks alot for identifying the issue? May I ask what kind of config/jade feature I should turn off tae get rid of this issue?

**Comment by SireAwfulThe1st** [comment]
> I'm pretty sure you have the mod "Jade", which I found out causes this.

**Comment by RubixDev** [comment]
Link to the corresponding issue on Jade: https://github.com/Snownee/Jade/issues/361

As I commented there, I think I found the source of the issue, but am not too sure about how to fix it yet. In the meantime disabling Jade's "Harvest Tool" feature will stop this from happening.

**Comment by Gamemassa** [comment]
There's actually also a mod called [AutoTools](https://www.curseforge.com/minecraft/mc-mods/autotools) that intentionally has this effect, so Sire, you should probably check to see if you have that mod in your modpack.

**Comment by SireAwfulThe1st** [comment]
> There's actually also a mod called [AutoTools](https://www.curseforge.com/minecraft/mc-mods/autotools) that intentionally has this effect, so @SireAwfulThe1st , you should probably check to see if you have that mod in your modpack.

Noted, but I don't use that mod anyways and I use my personal, non-public modpack so the only issue was jade, but thanks for the heads up still ^^
