### ISSUE TITLE
I'm pretty sure you have the mod "Jade", which I found out causes this.

### ISSUE THREAD

**Issue by SireAwfulThe1st** [RubixDev/Inventorio#298]
I'm pretty sure you have the mod "Jade", which I found out causes this.

_Originally posted by @Poundcaked in https://github.com/Lizard-Of-Oz/Inventorio/issues/296#issuecomment-1881798617_
           
 Hello, Thanks alot for identifying the issue? May I ask what kind of config/jade feature I should turn off tae get rid of this issue?

**Comment by BoardAnims** [comment]
> ```
>           I'm pretty sure you have the mod "Jade", which I found out causes this.
> ```
> 
> _Originally posted by @Poundcaked in [#296 (comment)](https://github.com/Lizard-Of-Oz/Inventorio/issues/296#issuecomment-1881798617)_
> 
> Hello, Thanks alot for identifying the issue? May I ask what kind of config/jade feature I should turn off tae get rid of this issue?

Looks like it's the "Harvest Tool" configuration which makes this bug happen.
Go to Jade Configuration > Plugin Settings > Minecraft > Set Harvest Tool to "OFF"
Sadly, this seems to remove the icons which tell you which tool the block can be mined with.
The config "Effective Tool" can remain "ON" but doesn't seem to change anything since it seems to be a "child" element of the "Harvest Tool" configuration.

**Comment by SireAwfulThe1st** [comment]
Hello  thx alot for the reply! been impatiently waiting for this resolution haha, cannae thank you enough! I'll see what I could do ^^

**Comment by Enderteck** [comment]
> > ```
> >           I'm pretty sure you have the mod "Jade", which I found out causes this.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Originally posted by @Poundcaked in [#296 (comment)](https://github.com/Lizard-Of-Oz/Inventorio/issues/296#issuecomment-1881798617)_
> > Hello, Thanks alot for identifying the issue? May I ask what kind of config/jade feature I should turn off tae get rid of this issue?
> 
> Looks like it's the "Harvest Tool" configuration which makes this bug happen. Go to Jade Configuration > Plugin Settings > Minecraft > Set Harvest Tool to "OFF" Sadly, this seems to remove the icons which tell you which tool the block can be mined with. The config "Effective Tool" can remain "ON" but doesn't seem to change anything since it seems to be a "child" element of the "Harvest Tool" configuration.

I have reported it to the Jade devs but thanks for the temporary fix. I didn't know you could disable only the harvesting tool thing.

**Comment by RubixDev** [comment]
Further discussion should be kept in #296
