### ISSUE TITLE
Why do the 1.20 versions not have the Utility Belt Restock from 1.19/older versions?

### ISSUE THREAD

**Issue by BoardAnims** [RubixDev/Inventorio#305]
Restocking the Utility Belt in 1.20 does not seem work at all...

In 1.19.2, if you have some torches in your offhand / active utility belt item and place a torch on the ground, break it and pick it up again, the torch will go straight back to your utility belt and restocks your torches.

In 1.20.1, if you have some torches in your offhand / active utility belt item and place a torch on the ground, break it and pick it up again, the torch will go to your hotbar / available inventory slot and not restock your torches.

Please add this tweak back to 1.20 it is driving me INSANE having to manually put the torches back in the utility belt.

**Comment by aMazeInRunar** [comment]
+1 This is really bothersome and it's driving me mad too.
