### ISSUE TITLE
[Compatability Request]: Curios, Aether, & Quark Menu

### ISSUE THREAD

**Issue by jzyserman** [RubixDev/Inventorio#307]
Please add the Curios, Aether, and Quark menu buttons to the expanded Inventorio GUI if they're in the modpack. See image below, thank you.

![image](https://github.com/Lizard-Of-Oz/Inventorio/assets/49997595/99d248bd-f376-464a-97aa-6a60f7f5109a)

**Comment by NathanMarsee** [comment]
Same with Cosmetic Armor Reworked and Inventory Crafter. These mods would be some really nice compatibility to have for modpacks (especially Curios and Quark sorting). The vanilla inventory toggle technically works, but it is inconvenient and makes the modpack feel unpolished. You might be able to look at how quark does its backpack for ideas on how to implement it.

**Comment by RubixDev** [comment]
Closing in favor of #318
