### ISSUE TITLE
Deep Pockets enchantment occasionally allows for illegal item stacks

### ISSUE THREAD

**Issue by Eshyyyyy** [RubixDev/Inventorio#314]
![Screenshot 2024-03-12 150435](https://github.com/Lizard-Of-Oz/Inventorio/assets/33994713/faca74d2-ae4d-416e-b7e3-cd4c51ea4e3e)
When running a wither rose farm I would occasionally see snowballs stack up to 32. This is normally impossible as snowballs can only stack up to 16.

**Comment by RubixDev** [comment]
Duplicate of #190
