### ISSUE TITLE
Deep Pockets Enchantment & Tool Slots disabled when going to another dimension until you open inventory

### ISSUE THREAD

**Issue by Eshyyyyy** [RubixDev/Inventorio#315]
When you travel to the Nether or End (or to the Overworld if in Nether or End) the mod will not work at all until you open your inventory. Tool slots/offhand are not available until you open your inventory

**Comment by CryoNine** [comment]
> this just got fixed in v1.10.0

this still happens in 2025 with 1.19.4 fabric. Not that annoying, just wanted to mention
