### ISSUE TITLE
Trinkets and Curios integration (and possible compat with other such mods)

### ISSUE THREAD

**Issue by RubixDev** [RubixDev/Inventorio#318]
As has already often been requested, better integration with Trinkets on Fabric and Curios on Forge would be preferable. Currently, players have to always switch between the custom Inventorio screen and the Vanilla inventory screen (where Trinkets/Curios add their stuff) when they want to access trinkets slots, which isn't made nicer by #267. I plan to add proper support for Trinkets and Curios so that their custom slots will also appear in the Inventorio screen.

Alternatively, it might be plausible to (re)try adding the Inventorio stuff to the vanilla screen just like all the other mods do (because this isn't just an issue with Trinkets/Curios but also Aether, Quark, Sound Muffler, TrashSlot, ...). This is probably difficult with Deep Pockets though and very error prone which is why LizardOfOz made it a separate screen in the first place. But maybe there's some ways to go with providing an option to at least add the tool belt and utility belt to the vanilla screen for better but not perfect compat with other mods, while still keeping the custom screen and adding integrations for some super widely used mods like Trinkets/Curios.

Previous issues regarding Trinkets:
- #71
- #129
- #181
- #246
- #248
- #317

Previous issues regarding Curios:
- #192
- #201
- #307

Instead of blessing any one of these as "the one", I decided to open this new one and point all the other ones here.

---

To-do:

- [x] integrate Trinkets in the Inventorio screen: fbaa9a6f63eba18ebd2c121cfd1683e006d6eb07, 5fc7ba2
  - [X] the trinket slots don't seem to update properly when switching between the screens which allows for duping: 9f6e171981d232c2f078a1dacbf6cd7fa026de48
  - [X] add an option to disable this in the global settings in case it introduces bugs in the future: df2af15
- [X] integrate Curios in the Inventorio screen: 7472828, 64c8723
  - [X] add an option to disable this in the global settings in case it introduces bugs in the future: df2af15
  - [X] player option to have curios open by default: f58f5fc
  - [X] when integration disabled, still show a button for the normal curios screen: 9f71e02
- [ ] #324
- [X] when deep pockets is equipped/unequipped some things don't update properly until the screen is re-opened. This isn't strictly just Trinkets/Curios stuff but I'll add it here anyway: d9b95a2

**Comment by Spiderfffun** [comment]
It might be a less breaking option to add the deep pockets UI underneath the normal inventory.
