### ISSUE TITLE
[Bug] Minor Conflict with REI (Fabric 1.20.4)

### ISSUE THREAD

**Issue by Gamemassa** [RubixDev/Inventorio#322]
Hi, not sure if this is related to my other active thread (about the extra slots not showing up in Creative mode), but I think Inventorio is causing a minor conflict with REI when in Creative mode. Normally when you click on items in REI it drops them into your inventory, but with Inventorio also installed, when in Creative mode if you try to give items to yourself with REI, they don't show up right away. Instead you have to switch to Survival mode, and close/reopen your inventory, and _then_ the items pop in.

**Comment by RubixDev** [comment]
The issue wasn't actually REI specific, it also occured with e.g. the `/give` command while the creative inventory was open. It should be fixed now though. If you want to try it out without waiting for the next release you can download the build artifacts from the [latest CI run](https://github.com/RubixDev/Inventorio/actions/runs/8462492872).

**Comment by Gamemassa** [comment]
Yup, confirmed. Definitely fixed in the latest version of Inventorio. Thanks again for the quick response!
