### ISSUE TITLE
Crash on newest version? (v1.10.2)

### ISSUE THREAD

**Issue by BoardAnims** [RubixDev/Inventorio#333]
Crash on the newest release as of now. (Inventorio v1.10.2 for MC 1.20.x)
May be due to the hotfix.

[latest.log](https://github.com/RubixDev/Inventorio/files/14817134/latest.log)

**Comment by RubixDev** [comment]
Yup, I'm already aware of this and a fix is [on its way](https://github.com/Fallen-Breath/conditional-mixin/issues/6)
