### ISSUE TITLE
Player inventory needs to be centered

### ISSUE THREAD

**Issue by rollercobester** [RubixDev/Inventorio#334]
So with the addition of another row on the side in the player's inventory, it has a larger width but for some reason is not being positioned in the center. You can see this clearly by comparing the inventory to the hotbar.

**Comment by RubixDev** [comment]
This is currently done on purpose to keep the normal slots in the exact same position as they are in the vanilla inventory. This makes switching between the two less jarring. I'll consider adding a player setting for this though as I can understand how some people would prefer to have it centered.
