### ISSUE TITLE
Forge 1.20.4

### ISSUE THREAD

**Issue by DuelMagicians** [RubixDev/Inventorio#342]
Is there going to be an update for forge 1.20.4?

**Comment by DuelMagicians** [comment]
I am aware there is a neoforge and fabric version. I am currently using forge only because I have mods that don't support either at the moment.

**Comment by RubixDev** [comment]
I understand that some mods still only support Forge, but I will personally not support Forge for any version that NeoForge exists for. NeoForge is the new and improved Forge made by mostly the same team and all Forge mods should migrate to NeoForge. I suggest opening issue tickets on those other mods instead, requesting NeoForge support.
