### ISSUE TITLE
[Suggestions] "Deep pocket" slots visible when opening the containers

### ISSUE THREAD

**Issue by DanteTooMayCry** [RubixDev/Inventorio#345]
Great that the mod was adopted. Inventorio has huge potential.

I'm not sure how difficult it is to do (because I don't think I've ever seen it in any mod) and I'm surprised that I don't find such suggestions, but I would like to suggest making the "deep pocket" slots (and even all inventorio screen) visible when opening the containers. I realize that it is not possible to access all of them, because there are separate screens for each block, but only for the basic ones. Like chests, furnace, crafting table, anvil, enchanting table, etc. And eventual for some of the more famous mods. Or prepare some integration method for creators of other mods.

I once saw an interesting idea on reddit:

https://www.reddit.com/r/minecraftsuggestions/comments/wi0tg8/upgrade_to_minecrafts_inventory_with_pictures/

This is about images number 5 and 6 where the container is not opened in one window with player inventory. And instead next to it, so you can see the entire inventory screen

**Comment by RubixDev** [comment]
I agree that this would be nice to have, but there are a couple of reasons why the extra slots are not currently visible in containers, and why that will likely also stay that way.

- This would require changing or overwriting _every_ container screen. That's not only lots of work, but would also introduce many more bugs and incompatibilities. Currently Inventorio only adds a replacement for the survival inventory screen, but that alone is already the cause for _many_ issues.
- There are enough examples of other things also not being available when having containers open. For vanilla that's the armor and offhand slots, also other mods such as Trinkets only add things to the main inventory screen.
- In my personal opinion this also helps with balancing a bit. Just adding more slots (like Deep Pockets does) is a very common request, but I think any extra slots should have some sort of disadvantage. And only being able to access these slots in the main inventory screen is one such disadvantage that just comes for free.

Maybe if some other mod comes along which makes screens behave like in those images 5 and 6, Inventorio could hook into that for the Inventorio addons.
