### ISSUE TITLE
Enchantment Descriptions Support

### ISSUE THREAD

**Issue by WenXin20** [RubixDev/Inventorio#58]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

Could support for the Enchantment Descriptions mod be added? For support to be added, only `enchantment.inventorio.deep_pockets.desc` would need to be added to the lang files.

**Comment by RubixDev** [comment]
This has been added years ago in ff877b52f5d1dc5e999b251217f133ee04aeb895
