### ISSUE TITLE
[Suggestion] Corpse compat?

### ISSUE THREAD

**Issue by coldloaded** [RubixDev/Inventorio#83]
Since this mod prodives Gravestone compatibility, is there any chance it will be updated with a Corpse compat? 
And switching from Corpse to Gravestone is not an option for me, because of how much Corpse's visuals helps, especially in multiplayer.

**Comment by RubixDev** [comment]
This will have to be reported to the Corpse mod. Inventorio provides an API they can use, and for Fabric there are already some grave mods supporting Inventorio (I know about Forgotten Graves, "You're in Grave Danger", and Universal Graves).
